# -*- coding: utf-8 -*-
"""Inheritance_pakinglot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRKxNj5dmMeu4TlpmoWfhRzlkptb0wxE
"""

cti

import datetime
from datetime import datetime, timedelta
import time
from time import sleep
class Car:
  def __init__(self,number_plate,owner_name):
    self.number_plate = number_plate
    self.owner_name = owner_name

class parking_ticket(Car):
  def __init__(self,car1,entry_time1):
    self.car = car1
    self.entry_time = entry_time1
    self.exit_time = None
    self.fee=0

  def calculate_fee(self):
    self.exit_time = datetime.now()
    duration = self.exit_time - self.entry_time
    minutes = duration.total_seconds()/60
    self.fee = minutes * 20
    return self.fee

class parking_lot:
  def __init__(self,capacity):
    self.capacity = capacity
    self.parked_cars = {} #No.Plate:ParkingTicket===dl01 : ticket1

  def park_car(self,car,minutes_ago=0):
    if len(self.parked_cars) >= self.capacity:
      print("parking full")
    else :
      entry_time=datetime.now() - timedelta(minutes=minutes_ago)
      #ticket = parking_ticket(car,datetime.now())
      ticket = parking_ticket(car,entry_time)
      self.parked_cars[car.number_plate] = ticket #adding item in dict
  def display(self):
      for k,v in self.parked_cars.items():
        print("parked successfully",k,v.car.owner_name)
      #print("car parked", self.parked_cars)

  def release_car(self,plate_number):
    ticket=self.parked_cars.pop(plate_number)
    ticket.calculate_fee()
    #print("car released and fee=",ticket.fee)
    print("car with plate number", plate_number, "released and fee=",ticket.fee)

#object
car1= Car("DL0001","pradeep")
car2= Car("DL0002","raks")
car3= Car("DL0003","ram")
car4= Car("DL0004","abc")
car5= Car("DL0005","xyz")


'''p1=parking_ticket(car1,datetime.now())
p2=parking_ticket(car2,datetime.now())
p3=parking_ticket(car3,datetime.now())
p4=parking_ticket(car4,datetime.now())
p5=parking_ticket(car5,datetime.now())'''


#main
PL=parking_lot(5)
'''PL.park_car(car1)
PL.park_car(car2)
PL.park_car(car3)
PL.park_car(car4)
PL.park_car(car5)'''
PL.display()

# Park cars (simulating they came in at different times)
PL.park_car(car1, minutes_ago=15)
PL.park_car(car2, minutes_ago=10)
PL.park_car(car3, minutes_ago=8)
PL.park_car(car4, minutes_ago=5)
PL.park_car(car5, minutes_ago=2)

# Display parked cars before releasing
print("\nCars parked before release:")
PL.display()

releasecar1=PL.release_car("DL0001")

releasecar2=PL.release_car("DL0002")
PL.display()

